"""
Property-based tests for the operator approval gate using Hypothesis.

**Validates: Requirements 2.5**

Property 4: No messages dispatched without explicit operator approval
- For any campaign created by an Automation_Rule or reaching its scheduled time,
  the Sending_Queue SHALL contain zero dispatched messages for that campaign
  until an operator explicitly approves it (status transitions through
  "pending_approval" → "approved").
- Direct transitions from draft→sending, draft→approved, scheduled→sending,
  and scheduled→approved are all invalid.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from hypothesis import given, settings, assume
from hypothesis import strategies as st

from blueprints.campaign_bp import CampaignService, VALID_TRANSITIONS


# ---------------------------------------------------------------------------
# States and strategies
# ---------------------------------------------------------------------------
# Pre-approval states: states a campaign is in before operator approval
PRE_APPROVAL_STATES = ["draft", "scheduled", "pending_approval"]

# States that directly enable message dispatch
DISPATCH_STATES = ["sending", "approved"]

# Build pairs of (pre_approval_state, dispatch_state) that should be blocked
# unless the proper approval path is followed
BLOCKED_DIRECT_DISPATCH_PAIRS = [
    (from_state, to_state)
    for from_state in ["draft", "scheduled"]
    for to_state in DISPATCH_STATES
    if to_state not in VALID_TRANSITIONS.get(from_state, set())
]

# Campaign types that can be generated by automation or scheduled
AUTOMATION_CAMPAIGN_TYPES = ["promotional", "transactional", "reactivation"]

# Strategies
pre_approval_states = st.sampled_from(PRE_APPROVAL_STATES)
blocked_pairs = st.sampled_from(BLOCKED_DIRECT_DISPATCH_PAIRS)
campaign_names = st.text(
    alphabet=st.characters(whitelist_categories=("L", "N", "P", "Z")),
    min_size=1,
    max_size=50,
)
campaign_types = st.sampled_from(AUTOMATION_CAMPAIGN_TYPES)
operator_names = st.text(
    alphabet=st.characters(whitelist_categories=("L", "N")),
    min_size=1,
    max_size=30,
)


# ---------------------------------------------------------------------------
# Mock helpers
# ---------------------------------------------------------------------------
class MockCursor:
    """Mock MySQL cursor with dictionary=True support."""

    def __init__(self):
        self.executed = []
        self.fetchone_result = None
        self.fetchall_result = []
        self.lastrowid = 1
        self._closed = False

    def execute(self, sql, params=None):
        self.executed.append((sql, params))

    def fetchone(self):
        return self.fetchone_result

    def fetchall(self):
        return self.fetchall_result

    def close(self):
        self._closed = True


class MockConnection:
    """Mock MySQL connection."""

    def __init__(self, cursor_instance=None):
        self._cursor = cursor_instance or MockCursor()
        self._committed = False
        self._rolled_back = False
        self._closed = False

    def cursor(self, dictionary=False):
        return self._cursor

    def start_transaction(self):
        pass

    def commit(self):
        self._committed = True

    def rollback(self):
        self._rolled_back = True

    def close(self):
        self._closed = True


# ---------------------------------------------------------------------------
# Property Tests
# ---------------------------------------------------------------------------
class TestApprovalGateProperty:
    """Property-based tests for the approval gate — Property 4."""

    @given(pair=blocked_pairs)
    @settings(max_examples=500)
    def test_no_direct_transition_to_dispatch_states_without_approval(self, pair: tuple):
        """
        Property: For any campaign in draft or scheduled state, a direct
        transition to 'approved' or 'sending' is rejected. This ensures
        no messages can be dispatched without going through
        pending_approval → approved → sending.

        **Validates: Requirements 2.5**
        """
        from_state, to_state = pair

        cursor = MockCursor()
        cursor.fetchone_result = {"id": 1, "status": from_state}
        conn = MockConnection(cursor)
        service = CampaignService(lambda: conn)

        try:
            service.transition_state(1, to_state, "automation_system")
            assert False, (
                f"Transition '{from_state}' → '{to_state}' should have been blocked "
                f"(approval gate violation) but succeeded"
            )
        except ValueError as e:
            assert "Invalid transition" in str(e), (
                f"ValueError should indicate invalid transition, got: {e}"
            )

    @given(campaign_type=campaign_types, operator=operator_names)
    @settings(max_examples=200)
    def test_pending_approval_cannot_skip_to_sending(self, campaign_type: str, operator: str):
        """
        Property: A campaign in pending_approval state cannot skip directly
        to 'sending' — it must first be approved. This ensures that even
        after submission for approval, the campaign cannot bypass the
        approval step.

        **Validates: Requirements 2.5**
        """
        assume(len(operator.strip()) > 0)

        cursor = MockCursor()
        cursor.fetchone_result = {"id": 1, "status": "pending_approval"}
        conn = MockConnection(cursor)
        service = CampaignService(lambda: conn)

        try:
            service.transition_state(1, "sending", operator)
            assert False, (
                "Transition 'pending_approval' → 'sending' should be blocked; "
                "must go through 'approved' first"
            )
        except ValueError as e:
            assert "Invalid transition" in str(e), (
                f"ValueError should indicate invalid transition, got: {e}"
            )

    @given(
        campaign_type=campaign_types,
        operator=operator_names,
    )
    @settings(max_examples=200)
    def test_approval_requires_pending_approval_state(self, campaign_type: str, operator: str):
        """
        Property: The approve_campaign() method only works when the campaign
        is in 'pending_approval' state. Attempting to approve from any other
        pre-dispatch state raises ValueError, ensuring the full approval path
        is enforced.

        **Validates: Requirements 2.5**
        """
        assume(len(operator.strip()) > 0)

        # Test that approve_campaign rejects campaigns not in pending_approval
        for state in ["draft", "scheduled"]:
            cursor = MockCursor()
            cursor.fetchone_result = {
                "id": 1,
                "status": state,
                "segment_id": 1,
                "template_id": 1,
            }
            conn = MockConnection(cursor)
            service = CampaignService(lambda: conn)

            try:
                service.approve_campaign(1, operator)
                assert False, (
                    f"approve_campaign() should reject campaign in '{state}' state "
                    f"but it succeeded"
                )
            except ValueError as e:
                assert "pending_approval" in str(e), (
                    f"Error should reference 'pending_approval' requirement, got: {e}"
                )

    @given(
        from_state=st.sampled_from(["draft", "scheduled"]),
        campaign_type=campaign_types,
    )
    @settings(max_examples=200)
    def test_only_valid_path_to_sending_is_through_approval(self, from_state: str, campaign_type: str):
        """
        Property: For any automation-generated or scheduled campaign, the only
        valid path to 'sending' state is:
        draft/scheduled → pending_approval → approved → sending.

        We verify that from draft/scheduled, the only transitions to a
        dispatch-enabling state go through pending_approval first.

        **Validates: Requirements 2.5**
        """
        # From draft or scheduled, only valid targets are those in VALID_TRANSITIONS
        allowed = VALID_TRANSITIONS.get(from_state, set())

        # 'sending' and 'approved' must NOT be directly reachable
        assert "sending" not in allowed, (
            f"'sending' should not be directly reachable from '{from_state}'"
        )
        assert "approved" not in allowed, (
            f"'approved' should not be directly reachable from '{from_state}'"
        )

        # 'pending_approval' MUST be reachable (it's the gateway to approval)
        assert "pending_approval" in allowed, (
            f"'pending_approval' must be reachable from '{from_state}' "
            f"to enable the approval workflow"
        )

    @given(operator=operator_names)
    @settings(max_examples=200)
    def test_submit_for_approval_is_required_gateway(self, operator: str):
        """
        Property: submit_for_approval() is the only way to move a campaign
        from draft/scheduled into the approval workflow. It correctly
        transitions to pending_approval state, enforcing that dispatch
        cannot happen without this explicit step.

        **Validates: Requirements 2.5**
        """
        assume(len(operator.strip()) > 0)
        call_count = [0]

        def get_conn():
            call_count[0] += 1
            if call_count[0] == 1:
                # For submit_for_approval (write connection)
                c = MockCursor()
                c.fetchone_result = {"id": 1, "status": "draft"}
                return MockConnection(c)
            else:
                # For get_campaign (read after transition)
                c = MockCursor()
                c.fetchone_result = {
                    "id": 1,
                    "status": "pending_approval",
                    "name": "Auto Campaign",
                }
                return MockConnection(c)

        service = CampaignService(get_conn)
        result = service.submit_for_approval(1, operator)
        assert result["status"] == "pending_approval", (
            f"submit_for_approval should transition to 'pending_approval', "
            f"got '{result['status']}'"
        )
